# Generated by Django 4.2.6 on 2024-01-01 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_notification_alter_item_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={},
        ),
        migrations.RemoveField(
            model_name='notification',
            name='name',
        ),
    ]
